# Generated by Django 5.0.3 on 2026-02-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="siape", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(max_length=1024)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
