# Generated by Django 5.0.3 on 2026-02-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="id",
            field=models.IntegerField(
                db_column="siape", primary_key=True, serialize=False
            ),
        ),
    ]
