# Generated by Django 5.2.8 on 2026-02-20 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_professor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(unique=True)),
                ('nivel', models.CharField()),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.professor')),
            ],
        ),
    ]
